// priority: 5000
const $CompoundTag = Java.loadClass('net.minecraft.nbt.CompoundTag')
const $ListTag = Java.loadClass('net.minecraft.nbt.ListTag')
const $ClipContext = Java.loadClass('net.minecraft.world.level.ClipContext')
const $ClipContextBlock = Java.loadClass('net.minecraft.world.level.ClipContext$Block')
const $ClipContextFluid = Java.loadClass('net.minecraft.world.level.ClipContext$Fluid')
const $Operation = Java.loadClass('net.minecraft.world.entity.ai.attributes.AttributeModifier$Operation')
const $AttributeModifier = Java.loadClass('net.minecraft.world.entity.ai.attributes.AttributeModifier')

const $LivingEntity = Java.loadClass('net.minecraft.world.entity.LivingEntity')
const $CommonUtil = Java.loadClass('net.tigereye.chestcavity.util.CommonUtil')
const $Integer = Java.loadClass('java.lang.Integer')
const $MobEffectInstance = Java.loadClass('net.minecraft.world.effect.MobEffectInstance')
const $PathfinderMob = Java.loadClass('net.minecraft.world.entity.PathfinderMob')


// const $SummonedZombie = Java.loadClass('io.redspace.ironsspellbooks.entity.mobs.SummonedZombie')
// const $ExtendedEvokerFang = Java.loadClass('io.redspace.ironsspellbooks.entity.spells.ExtendedEvokerFang')

const $ItemEntity = Java.loadClass('net.minecraft.world.entity.item.ItemEntity')

// const $FleshBlob = Java.loadClass('com.github.elenterius.biomancy.entity.mob.fleshblob.FleshBlob')
const $BundleTooltip = Java.loadClass('net.minecraft.world.inventory.tooltip.BundleTooltip')
const $NonNullList = Java.loadClass('net.minecraft.core.NonNullList')
const $ItemStack = Java.loadClass('net.minecraft.world.item.ItemStack')
const $ToolAction = Java.loadClass('net.minecraftforge.common.ToolAction')
// const $InfinityStats = Java.loadClass('net.lerariemann.infinity.registry.var.ModStats')
// const $EntityCastData = Java.loadClass('io.redspace.ironsspellbooks.spells.EntityCastData')
// const $AbstractConeProjectile = Java.loadClass('io.redspace.ironsspellbooks.entity.spells.AbstractConeProjectile')
// const $ISSDamageSources = Java.loadClass('io.redspace.ironsspellbooks.damage.DamageSources')
// const $ISSDamageTypes = Java.loadClass('io.redspace.ironsspellbooks.damage.ISSDamageTypes')
const $ParticleTypes = Java.loadClass('net.minecraft.core.particles.ParticleTypes')
// const $SpellDamageSource = Java.loadClass('io.redspace.ironsspellbooks.damage.SpellDamageSource')
const $Player = Java.loadClass('net.minecraft.world.entity.player.Player')
// const $DevourJaw = Java.loadClass('io.redspace.ironsspellbooks.entity.spells.devour_jaw.DevourJaw')
// const $StompAoe = Java.loadClass('io.redspace.ironsspellbooks.entity.spells.StompAoe')
const $BlockParticleOption = Java.loadClass('net.minecraft.core.particles.BlockParticleOption')
const $PotionUtils = Java.loadClass('net.minecraft.world.item.alchemy.PotionUtils')
// const $WitherSkullProjectile = Java.loadClass('io.redspace.ironsspellbooks.entity.spells.WitherSkullProjectile')
// const $DeployerFakePlayer = Java.loadClass('com.simibubi.create.content.kinetics.deployer.DeployerFakePlayer')
